# Generated by Django 3.1.7 on 2021-04-08 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=35, null=True)),
                ('job_country', models.CharField(blank=True, max_length=300, null=True)),
                ('job_adress', models.CharField(blank=True, max_length=300, null=True)),
                ('job_zipcode', models.CharField(blank=True, max_length=300, null=True)),
                ('payment_type', models.CharField(choices=[('cash_1', 'cash'), ('click_2', 'click'), ('payme_3', 'payme'), ('oson_4', 'oson'), ('visa_5', 'visa'), ('cryptocurrency_6', 'cryptocurrency'), ('ewallet_7', 'ewallet')], default='cash_1', max_length=20)),
                ('salary_type', models.CharField(choices=[('fixed_1', 'fixed'), ('hourly_1', 'hourly'), ('by_project_1', 'by_project')], default='fixed_1', max_length=100)),
                ('wage_min', models.CharField(max_length=100)),
                ('wage_max', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('uzs_1', 'uzs'), ('usd_2', 'usd'), ('eur_3', 'eur'), ('rubl_4', 'rubl')], default='uzs_1', max_length=100)),
                ('employee_type', models.CharField(choices=[('online_1', 'online'), ('offline_2', 'offline')], default='offline_2', max_length=100)),
                ('preffered_gender', models.CharField(choices=[('male_1', 'male'), ('female_2', 'female'), ('any_3', 'any')], default='male_1', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('employed', 'Employed'), ('archived', 'Archived')], default='active', max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('experience', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job.job')),
            ],
        ),
    ]
